name: Auto Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deployment:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets. USER_NAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
          　　　　sudo su -
            cd /opt/twitter-api/
            git pull origin main
