name: Auto Deploy to Server

on:
  push:
    branches:
      - main  # main ブランチにプッシュされたときに実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

#    - name: Set up SSH
#      uses: webfactory/ssh-agent@v0.4.0
#      with:
#        ssh-private-key: ${{ secrets.PRIVATE_KEY }}

    - name: Deploy to server
      with:
        ssh-private-key: ${{ secrets.PRIVATE_KEY }}
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USER_NAME }}@${{ secrets.HOST_NAME }} -p 22 'cd /path/to/your/app && git pull origin main'
